#!/usr/bin/env python

"""image_download.py: downloads all TMA images from the HPA to a specified directory given a csv file generated by get_image_urls_from_gene_list.py 

usage: image_download.py <input_file> <output folder>
"""
# CHANGE LOG:
# 06-18-2013 MK initial build
# 08-29-2013 TC clean up and standardize code
# 07-11-2014 TC additional code clean up and documentation
# 07-13-2014 TC fix to accomodate new HPA website html

__author__ = "Marc Halushka, Toby Cornish"
__copyright__ = "Copyright 2014, Johns Hopkins University"
__credits__ = ["Marc Halushka", "Toby Cornish"]
__license__ = "GPL"
__version__ = "1.0.0"
__maintainer__ = "Toby Cornish"
__email__ = "tcornis3@jhmi.edu"

import urllib
import csv
import sys
import os
import traceback

def main(infile,outdir):
	try:
		if not os.path.exists(outdir):
			# make the directory if it doesn't exist
			os.makedirs(outdir)

		with open(infile, "r") as f:
			#f.readline() #skip the header
			reader = csv.DictReader(f)
			for image in reader:
				url = image['imageURL']
				url = url.replace('_medium','') # get the full resolution images
				image_name = url.replace('http://www.proteinatlas.org/images/','')
				image_name = image_name.replace('/', '_')
				print '%s -> %s' % (url,image_name)
				
				image_data = urllib.urlopen(url).read()
				# Open output file in binary mode, write, and close.
				with open(os.path.join(outdir,image_name),'wb') as fout:
					#This could be a good place to have the images go directly into a unique folder
					fout.write(image_data)
				
		print "Complete."

	except Exception,e: # catch any errors & pass on the message
		print 'Caught Exception: %s' % str(e)
		print traceback.format_exc()
		

if __name__ == '__main__':
	if len(sys.argv) != 3:
		print 'usage: %s <input_file> <output folder>' % os.path.basename(sys.argv[0])
		exit()
	else:
		main(sys.argv[1],sys.argv[2])
